setup.exe /IACCEPTSQLSERVERLICENSETERMS /IACCEPTPYTHONLICENSETERM /IACCEPTROPENLICENSETERMS /CONFIGURATIONFILE="c:\t\sql server unattended.ini"
setup.exe /Action=Uninstall /FEATURES=SQL,Tools /INSTANCENAME=MSSQLSERVER
