setup.exe /IACCEPTSQLSERVERLICENSETERMS /IACCEPTPYTHONLICENSETERM /IACCEPTROPENLICENSETERMS /CONFIGURATIONFILE="c:\t\sql server unattended.ini"
setup.exe /Action=Uninstall /FEATURES=SQL,Tools /INSTANCENAME=MSSQLSERVER /QUIET="False" /QUIETSIMPLE="True" /SUPPRESSPRIVACYSTATEMENTNOTICE="True" /IACCEPTSQLSERVERLICENSETERMS /IACCEPTPYTHONLICENSETERM /IACCEPTROPENLICENSETERMS 
